### ISSUE TITLE
Add attribute to control spacing/gap between dashes.

### ISSUE THREAD

**Issue by adifyr** [Biscozum/mobkit_dashed_border#10]
Hi. Thank you for the package. Could you possibly add an attribute to control the spacing/gap between dashes? For example, something like `dashGapLength` or `dashSpacing`? Here is what example code would look like:

```dart
Container(
  decoration: BoxDecoration(
    border: DashedBorder.all(dashLength: 16.0, dashGapLength: 8.0), // Or "dashSpacing".
    borderRadius: BorderRadius.circular(8.0),
  )
);
```

**Comment by hamzavedatBis** [comment]
Hi, we’ve reviewed your request and included it in the next release. You can track the progress here. However, you should keep in mind that if the spacing and length values you provided aren't exactly divisible by the shape's perimeter, the values will be rounded to the nearest appropriate number. This package does this to ensure that all corners appear with equal length and maintain a consistent, orderly appearance.

**Comment by hamzavedatBis** [comment]
@adifyr  You can use v0.0.7 on pub.dev
